name: Python CI (Standard + Security Ready)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install Tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit safety
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint Check
      run: |
        flake8 . --select=E9,F63,F7,F82 --show-source --statistics

    - name: Security Scan (Bandit)
      run: |
        bandit -r . || true

    - name: Dependency Scan
      run: |
        safety check || true
